### ISSUE TITLE
Change behavior of services (use ods-control instead of opendnssec-signer and opendnssec-enforcer init scripts)

### ISSUE THREAD

**Issue by mave007** [icann-dns/puppet-opendnssec#2]
## Affected opendnssec startup

Puppet: all
Ruby: all
Distribution: all
Module version: current

## How to reproduce (e.g Puppet code you use)

start opendnssec service or let puppet restart service once it has stopped.

## What are you seeing

OpenDNSSEC fails to start and to do the initial handshake with the HSM:
```
Dec  5 22:49:11 iad01 ods-signerd: [engine] signer started (version 1.4.13), pid 24913
Dec  5 22:49:11 iad01 ods-signerd: [hsm] hsm_get_slot_id(): could not find token with the name OpenDNSSEC
Dec  5 22:49:11 iad01 ods-signerd: [engine] opening hsm failed (for engine recover)
Dec  5 22:49:11 iad01 ods-signerd: [engine] signer shutdown
```

## What behaviour did you expect instead

opendnssec service (signer and enforcer) should start

## Any additional information you'd like to impart

https://github.com/icann-dns/puppet-opendnssec/blob/eac83bd76d7f40b313f7bbf8b717c38a29f18b7a/manifests/init.pp#L156

The process to start opendnssec needs to run in certain order alongside the HSM services in order to run. 

Seems like puppet can not manage via its usual init.d services this aspect, so it might be better to use `ods-control` instead for this.

**Comment by b4ldr** [comment]
do you think above pull is enough to fix this?

**Comment by b4ldr** [comment]
xenial is still failing will take a look later

**Comment by b4ldr** [comment]
I tried to use ods-control however it caused problems with puppets management of services.  however i looked at ods-control and all it does is ensure that the enforcer starts before the signer.  By chaining the services as i have in #3 should ensure this behaviour.  I have also added chaining to ensure that all configs are written before services are started.  @mave007 can you check the change and comment on its viability

**Comment by mave007** [comment]
Just as a note: I noticed after several tries and errors that when doing a manual restart, a double start call using `ods contro`l (ie `ods-hsmutil login; ods-control start ; ods-control start` ) makes things work again with correct PIDs marks and services as expected.
